

## Output du scraper marmiton 



l_recettes = 

[{'Recette': 'tarte-aux-poireaux-et-aux-lardons', 
'Liste des ingrédients': ['sel', 'poivre', '25 cl\nde crème fraîche', '100 g\nde fromage râpé', '400 g\nde lardons', '3\npoireaux', '140 g\nde beurre', '250 g\nde farine', "2 cuillères à soupe\nd' eau", '3\noeufs'], 'Lien vers la recette': 'https://www.marmiton.org/recettes/recette_tarte-aux-poireaux-et-aux-lardons_12850.aspx'}, 
{'Recette': 'quiche-poireaux-chevre-lardons', 'Liste des ingrédients': ['sel', 'poivre', '20 cl\nde crème fraîche', '3\npoireaux', '250 g\nde pâte brisée (ou une pâte toute prête)', '100 g\nde lardons fumés', '1\nfromage de chèvre (cottin, bûche...selon les goûts)', '3\noeufs', '10 cl\nde lait'], 'Lien vers la recette': 'https://www.marmiton.org/recettes/recette_quiche-poireaux-chevre-lardons_22275.aspx'},
{'Recette': 'tagliatelles-a-la-creme-de-poireaux', 'Liste des ingrédients': ['sel', 'poivre', 'beurre', '1 petit pot\nde crème fraîche', '150 g\nde lardons', '2\npoireaux', '500 g\nde tagliatelles', 'Parmesan'], 'Lien vers la recette': 'https://www.marmiton.org/recettes/recette_tagliatelles-a-la-creme-de-poireaux_20838.aspx'}, 
{'Recette': 'quiche-au-poireau-et-saumon-fume', 'Liste des ingrédients': ['muscade', 'sel', 'poivre', '4 cuillères à soupe\nde crème fraîche allégée', '50 g\nde gruyère râpé', '2\npoireaux', '1\npâte brisée', '4 tranches\nde saumon fumé', '2\noeufs', '6 cuillères à soupe\nde lait'], 'Lien vers la recette': 'https://www.marmiton.org/recettes/recette_quiche-au-poireau-et-saumon-fume_16938.aspx'}, 
{'Recette': 'fondue-de-poireaux', 'Liste des ingrédients': ['poivre du moulin', 'sel', '2 cuillères à soupe\nde crème fraîche', '1 cuillère à soupe\nde moutarde de Dijon', '30 g\nde beurre', '600 g\nde poireau', '2 cuillères à soupe\nde jus de citron'], 'Lien vers la recette': 'https://www.marmiton.org/recettes/recette_fondue-de-poireaux_20348.aspx'}, 
{'Recette': 'risotto-aux-poireaux', 'Liste des ingrédients': ['crème fraîche', 'beurre', '1\ncube de bouillon de légumes ou un Kub Or', '3\npoireaux de belle taille', '4 louches\nde riz pour risotto', '1\nvin blanc sec', 'parmesan râpé'], 'Lien vers la recette': 'https://www.marmiton.org/recettes/recette_risotto-aux-poireaux_19753.aspx'}, 
{'Recette': 'pave-de-saumon-sur-son-lit-de-poireaux', 'Liste des ingrédients': ['curry', 'huile', 'sel', 'poivre', '4\npoireaux', '4 pavés\nde saumon', '20 cl\nde crème fraîche épaisse'], 'Lien vers la recette': 'https://www.marmiton.org/recettes/recette_pave-de-saumon-sur-son-lit-de-poireaux_25136.aspx'}, 
{'Recette': 'potage-veloute-poireaux-pommes-de-terre', 'Liste des ingrédients': ['50 g\nde beurre', 'sel', 'poivre', 'crème fraîche', '2\npoireaux', '2\npommes de terre', '0.5 l\nde lait', "0.5 l\nd' eau", 'basilic ciselé'], 'Lien vers la recette': 'https://www.marmiton.org/recettes/recette_potage-veloute-poireaux-pommes-de-terre_18971.aspx'}, 
{'Recette': 'brick-au-thon-et-au-poireau', 'Liste des ingrédients': ['sel', 'poivre', '2 cuillères à soupe\nde crème fraîche', '1 cuillère à café\nde curry', '2\npoireaux "moyens"', '6 feuilles\nde brick', '250 g\nde thon en boîte', '1\noeuf'], 'Lien vers la recette': 'https://www.marmiton.org/recettes/recette_brick-au-thon-et-au-poireau_29421.aspx'}, 
{'Recette': 'papillote-de-saumon-super-fondant-aux-poireaux', 'Liste des ingrédients': ['sel', 'poivre', 'aneth', '2\noignons', '3\npoireaux', '1 filet\nde saumon par personne', 'crème'], 'Lien vers la recette': 'https://www.marmiton.org/recettes/recette_papillote-de-saumon-super-fondant-aux-poireaux_16801.aspx'}, 
{'Recette': 'tourte-poireaux-jambon-et-chevre', 'Liste des ingrédients': ['3\npoireaux', '1 rouleau\nde pâte feuilletée', '2\nchèvre frais', '100 g\nde dés de jambon', '25 cl\nde crème liquide', "2\njaunes d'oeuf"], 'Lien vers la recette': 'https://www.marmiton.org/recettes/recette_tourte-poireaux-jambon-et-chevre_24497.aspx'}, 
{'Recette': 'tarte-au-chevre-et-aux-poireaux', 'Liste des ingrédients': ['1 pincée\nde sel', '150 g\nde beurre', '300 g\nde farine', "2 cuillères à soupe\nd' épices orientale)", 'sel', 'poivre', 'emmental râpé', '2\npoireaux', '40 cl\nde crème fraîche épaisse', '4\noeufs', '1 verre\nde lait', '1\nbûche de chèvre (ou 150 gr de fromage de chèvre du même type)'], 'Lien vers la recette': 'https://www.marmiton.org/recettes/recette_tarte-au-chevre-et-aux-poireaux_18100.aspx'}]